name             'mongodb'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mongodb'
long_description 'Installs/Configures mongodb'
version          '0.1.0'
