source 'https://supermarket.chef.io/'

cookbook 'yum-epel', git: 'git@github.com:chef-cookbooks/yum-epel.git'
cookbook 'build-essential', 'git: git@github.com:opscode-cookbooks/build-essential.git'
cookbook 'ark', git: 'git://github.com/opscode-cookbooks/ark.git'
cookbook 'apt', git: 'git@github.com:opscode-cookbooks/apt.git'
cookbook 'homebrew', git: 'git@github.com:opscode-cookbooks/homebrew.git'

metadata

group :integration do
  cookbook 'apt'
  cookbook 'nodejs_test', :path => './test/cookbooks/nodejs_test'
end
